[theme]
primaryColor = "#1d4ed8"
backgroundColor = "#f7f9fc"
secondaryBackgroundColor = "#eff6ff"
textColor = "#0f172a"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
